### ISSUE TITLE
i18n translations

### ISSUE THREAD

**Issue by SpaceWhite** [SpaceWhite/inma#23]
# Description

Right now, the codebase only support i18n for landing page. We need to add more translations to different UIs

List of languages that need to be added initially
- English
- Japanese
- Chinese
- Korean
- Spanish

# TODO

- [ ] Add language support in user preference setup UI 
- [ ] Add language support for hospital description
 
# Closed criteria

- [ ] language support has
